# nixpacks.toml
[phases.setup]
nixPkgs = ["nodejs-20_x", "chromium"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = []

[start]
cmd = "node src/server.js"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "false"
PUPPETEER_EXECUTABLE_PATH = "/nix/store/*-chromium-*/bin/chromium"
NODE_ENV = "production"